# Generated by Django 2.1.4 on 2018-12-16 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_auto_20181216_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_order2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='order2',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.User_order2'),
        ),
        migrations.DeleteModel(
            name='User_order',
        ),
    ]
