# Generated by Django 2.1.4 on 2018-12-16 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20181216_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_order3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('order_number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user_order2',
            name='user',
        ),
        migrations.AlterField(
            model_name='order2',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.User_order3'),
        ),
        migrations.DeleteModel(
            name='User_order2',
        ),
    ]
