# Generated by Django 2.1.4 on 2018-12-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20181216_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order2',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='User_order3',
        ),
    ]
