# Generated by Django 2.1.4 on 2018-12-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20181216_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order2',
            name='number',
            field=models.IntegerField(),
        ),
    ]
