# Generated by Django 2.1.4 on 2018-12-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_user_order_topping_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_order',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
