# Generated by Django 2.1.4 on 2018-12-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_user_order_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_order',
            name='completed',
        ),
        migrations.AddField(
            model_name='user_order',
            name='status',
            field=models.CharField(default='initiated', max_length=64),
        ),
    ]
